### ISSUE TITLE
Don't try to override _ by default

### ISSUE THREAD

**Issue by peey** [erasaur/meteor-lodash#6]
Hey, 

In the discussion of ["Investigate swapping underscore with Lo-dash in meteor"](https://github.com/meteor/meteor/issues/1009), it's mentioned that meteor doesn't touch the existing underscore version because it may introduce bugs. 

Though overriding _ is intended as the package exports an _, but it doesn't work and I think that's why everything is working correctly, else things could break if meteor code started to use lodash.
So for safety, I think recommended way to include lodash should be just declaring `var _ = lodash` in your js files , so the declaration is limited to file scope and that way you get to use lodash and meteor code gets to use underscore.

Thoughts?

**Comment by erasaur** [comment]
Hm... you're probably right that swapping in lodash with a large project, like Meteor, could be a QA pain and might introduce some bugs/backwards compat issues. Though I'm not sure MDG is hesitating with the migration because they know lodash will break things for sure; rather it seems their hesitation stems from speculating that it could, which I suppose is fair enough a reason.

For the most part, though, I haven't found any issues replacing `_` globally, and I've been using lodash in quite a few projects already. Don't take my word for it though. Maybe you can take a look at this, if you haven't already: https://github.com/lodash/lodash/wiki/Migrating. 
If you aren't using underscore in such a way that lodash would break your application, it's probably okay to just replace it entirely. To my knowledge you shouldn't have to worry about breaking Meteor code by declaring `_ = lodash` in application level code, because that won't affect the packages that constitute Meteor.

Then again, there's no big downside with "importing" lodash in the files that you want to use it with `var _ = lodash`. To me it seems like it might result in a lot of tedious changes (i.e, having to edit a ton of files in the event of wanting to swap out lodash) and it seems error prone (i.e forgetting to add it and unknowingly using underscore). I guess if you need to use underscore in some places and lodash in others, you'll have to go down this path, but otherwise it seems like even more of a pain than swapping out the whole thing and fixing the few areas that might have broken.

By the way, there's another method as suggested in the thread you linked, which is to just remove the underscore dependency from `meteor-platform` and manually add those packages + lodash. That seems like it could work as well.

**Comment by peey** [comment]
Why do you think 

>  To my knowledge you shouldn't have to worry about breaking Meteor code by declaring _ = lodash in application level code, because that won't affect the packages that constitute Meteor.
> ?

Because that's my only concern here

**Comment by erasaur** [comment]
When the app gets bundled, each meteor package is compiled into its own file, which contents are wrapped in one big closure. Within this closure all dependencies are declared (e.g `var _ = Package.underscore._;`). In other words, no package leaks globals to other packages, and each package "imports" its own dependencies locally, so there really is no way for your application code to mess up meteor core.

**Comment by peey** [comment]
Oh, well that settles my concerns. Thanks!

**Comment by mitar** [comment]
You could also make this package `imply` `underscore` package.
